export const roomPermissionToLabel: Record<string, string> = {
  bankEnabled: 'Bank',
  casinoEnabled: 'Casino',
  meleeEnabled: 'Can Melee',
  shootEnabled: 'Can Shoot',
  bombEnabled: 'Can Bomb',
  hitEnabled: 'Can Hit',
  magicEnabled: 'Can Use Magic',
  robEnabled: 'Can Rob',
  daylightEnabled: 'Daylight System',
  turfEnabled: 'Gang Turf',
  hospitalEnabled: 'Hospital',
  safezoneEnabled: 'Safezone!',
  mwEnabled: 'MW',
  gymEnabled: 'Gym',
  taxiToEnabled: 'Can Taxi To',
  taxiFromEnabled: 'Can Taxi From',
};
